//! Known-answer tests for the values that go on the wire.
//!
//! Every other test in this crate checks that the code agrees with itself:
//! generate a chain, MAC something, verify it back. That catches logic errors
//! and catches nothing at all if a change moves *every* derived value together
//! — a swapped domain separator, a different truncation end, a dependency major
//! that quietly alters an output. Those all keep the round-trip green while
//! breaking every already-deployed node.
//!
//! So these vectors are absolute. They were generated by this implementation
//! rather than taken from a third party, which means they prove continuity, not
//! correctness against the spec — the primitives underneath are standard
//! SHA-256 and HMAC-SHA256, and the RustCrypto crates carry the NIST vectors
//! for those. What is pinned here is Signet's own layering on top: the
//! chain direction, the MAC-key domain separation, and the truncation.
//!
//! A failure here is not a test to update. It is a wire-format change, and
//! `PROTOCOL.md` and `CHANGELOG.md` move with it.

use signet_core::chain::{self, Chain, MAC_LEN};

const SEED: &[u8] = b"signet-fixed-seed-for-comparison";
const MSG: &[u8] = b"evacuate north of 5th st";

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

#[test]
fn chain_derivation_is_stable() {
    let chain = Chain::from_seed(SEED, 8);

    assert_eq!(
        hex(&chain.commitment()),
        "a3795606ae1562a259af3adf89fb46e9ef5c7b09abe7479dc608a8c56cec05a6",
        "commitment changed — every receiver anchored to the old value is now deaf"
    );
    assert_eq!(
        hex(&chain.key(5).unwrap()),
        "6f1f4fbe3faea162abb5d7a25ffcc2bb31f78bfc420264537ad61f574b426dc7",
        "disclosed key changed"
    );
    assert_eq!(
        hex(&chain.mac_key(5).unwrap()),
        "49fdf11ddd8891dee8c9a3f44c85001cf5cf684a6c49816d3e80540e44c9ea8a",
        "MAC-key derivation changed — check the domain separator"
    );
}

#[test]
fn mac_is_stable() {
    let chain = Chain::from_seed(SEED, 8);
    let mac_key = chain.mac_key(5).unwrap();
    let tag = chain::mac(&mac_key, MSG);

    assert_eq!(tag.len(), MAC_LEN);
    assert_eq!(
        hex(&tag),
        "28b9cb8765815d14018a395cb5216469",
        "MAC changed — check the truncation end, not just the primitive"
    );

    assert!(chain::verify_mac(&mac_key, MSG, &tag));
    assert!(!chain::verify_mac(
        &mac_key,
        b"evacuate south of 5th st",
        &tag
    ));
}

#[test]
fn the_mac_key_is_not_the_disclosed_key() {
    // The whole scheme rests on this: disclosing K[i] must not disclose the key
    // that authenticated interval i. If these ever match, TESLA is broken.
    let chain = Chain::from_seed(SEED, 8);
    assert_ne!(chain.key(5).unwrap(), chain.mac_key(5).unwrap());
}

#[test]
fn disclosure_verifies_against_the_pinned_commitment() {
    let chain = Chain::from_seed(SEED, 8);
    assert!(chain::verify_disclosure(
        &chain.commitment(),
        0,
        5,
        &chain.key(5).unwrap()
    ));
}
